"""empty message

Revision ID: 116156374d72
Revises: 14da9232dbb9
Create Date: 2022-12-11 21:31:26.767670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116156374d72'
down_revision = '14da9232dbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('note_id')

    # ### end Alembic commands ###
