"""empty message

Revision ID: 2011b27a7933
Revises: d5c82792e7e2
Create Date: 2022-11-21 11:30:18.370501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2011b27a7933'
down_revision = 'd5c82792e7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_period', sa.String(), nullable=True))
        batch_op.drop_column('time_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_period', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('end_period')

    # ### end Alembic commands ###
