"""empty message

Revision ID: c79317734de8
Revises: 2011b27a7933
Create Date: 2022-11-21 11:39:17.914914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79317734de8'
down_revision = '2011b27a7933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))
        batch_op.drop_column('end_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_period', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
